name: main-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Instalar dependencias
      run: |
        gem install xcpretty
        gem install xcpretty-travis-formatter
    - name: Compilar y ejecutar test unitarios
      run: |
        xcodebuild clean test -project Portfolio.xcodeproj -scheme MyApp -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" -enableCodeCoverage YES | xcpretty -f `xcpretty-travis-formatter`
